namespace MeAndMyDog.API.Models.DTOs;

/// <summary>
/// Security compliance report
/// </summary>
public class SecurityComplianceReportDto
{
    /// <summary>
    /// Report ID
    /// </summary>
    public string ReportId { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Report generation date
    /// </summary>
    public DateTimeOffset GeneratedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Report period start
    /// </summary>
    public DateTimeOffset PeriodStart { get; set; }

    /// <summary>
    /// Report period end
    /// </summary>
    public DateTimeOffset PeriodEnd { get; set; }

    /// <summary>
    /// Generated by user ID
    /// </summary>
    public string GeneratedBy { get; set; } = string.Empty;

    /// <summary>
    /// Overall compliance score (0-100)
    /// </summary>
    public double ComplianceScore { get; set; }

    /// <summary>
    /// Compliance status
    /// </summary>
    public string ComplianceStatus { get; set; } = "Compliant";

    /// <summary>
    /// Total number of security incidents
    /// </summary>
    public int TotalIncidents { get; set; }

    /// <summary>
    /// Critical incidents count
    /// </summary>
    public int CriticalIncidents { get; set; }

    /// <summary>
    /// High severity incidents count
    /// </summary>
    public int HighSeverityIncidents { get; set; }

    /// <summary>
    /// Average incident resolution time
    /// </summary>
    public TimeSpan AverageResolutionTime { get; set; }

    /// <summary>
    /// Number of unresolved incidents
    /// </summary>
    public int UnresolvedIncidents { get; set; }

    /// <summary>
    /// Total access attempts
    /// </summary>
    public long TotalAccessAttempts { get; set; }

    /// <summary>
    /// Blocked access attempts
    /// </summary>
    public long BlockedAccessAttempts { get; set; }

    /// <summary>
    /// Access success rate
    /// </summary>
    public double AccessSuccessRate { get; set; }

    /// <summary>
    /// Number of self-destructed messages
    /// </summary>
    public int SelfDestructedMessages { get; set; }

    /// <summary>
    /// Number of secure messages
    /// </summary>
    public int SecureMessages { get; set; }

    /// <summary>
    /// Compliance violations found
    /// </summary>
    public List<ComplianceViolationDto> Violations { get; set; } = new();

    /// <summary>
    /// Security metrics by day
    /// </summary>
    public List<DailySecurityMetricsDto> DailyMetrics { get; set; } = new();

    /// <summary>
    /// Recommendations for improvement
    /// </summary>
    public List<string> Recommendations { get; set; } = new();
}